//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.EntityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchemeObj", Namespace="http://schemas.datacontract.org/2004/07/ServiceEndpoint")]
    [System.SerializableAttribute()]
    public partial class SchemeObj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string createdByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createdOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal discountPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expiredByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime modifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> primaryCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal revenueGeneratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> secondaryCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int unitsBookedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                if ((object.ReferenceEquals(this.createdByField, value) != true)) {
                    this.createdByField = value;
                    this.RaisePropertyChanged("createdBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdOn {
            get {
                return this.createdOnField;
            }
            set {
                if ((this.createdOnField.Equals(value) != true)) {
                    this.createdOnField = value;
                    this.RaisePropertyChanged("createdOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal discountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                if ((this.discountPercentField.Equals(value) != true)) {
                    this.discountPercentField = value;
                    this.RaisePropertyChanged("discountPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expiredBy {
            get {
                return this.expiredByField;
            }
            set {
                if ((object.ReferenceEquals(this.expiredByField, value) != true)) {
                    this.expiredByField = value;
                    this.RaisePropertyChanged("expiredBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isExpired {
            get {
                return this.isExpiredField;
            }
            set {
                if ((this.isExpiredField.Equals(value) != true)) {
                    this.isExpiredField = value;
                    this.RaisePropertyChanged("isExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.modifiedByField, value) != true)) {
                    this.modifiedByField = value;
                    this.RaisePropertyChanged("modifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime modifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                if ((this.modifiedOnField.Equals(value) != true)) {
                    this.modifiedOnField = value;
                    this.RaisePropertyChanged("modifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> primaryCategoryId {
            get {
                return this.primaryCategoryIdField;
            }
            set {
                if ((this.primaryCategoryIdField.Equals(value) != true)) {
                    this.primaryCategoryIdField = value;
                    this.RaisePropertyChanged("primaryCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal revenueGenerated {
            get {
                return this.revenueGeneratedField;
            }
            set {
                if ((this.revenueGeneratedField.Equals(value) != true)) {
                    this.revenueGeneratedField = value;
                    this.RaisePropertyChanged("revenueGenerated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> secondaryCategoryId {
            get {
                return this.secondaryCategoryIdField;
            }
            set {
                if ((this.secondaryCategoryIdField.Equals(value) != true)) {
                    this.secondaryCategoryIdField = value;
                    this.RaisePropertyChanged("secondaryCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shortCode {
            get {
                return this.shortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.shortCodeField, value) != true)) {
                    this.shortCodeField = value;
                    this.RaisePropertyChanged("shortCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int unitsBooked {
            get {
                return this.unitsBookedField;
            }
            set {
                if ((this.unitsBookedField.Equals(value) != true)) {
                    this.unitsBookedField = value;
                    this.RaisePropertyChanged("unitsBooked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsAndQty", Namespace="http://schemas.datacontract.org/2004/07/ServiceEndpoint")]
    [System.SerializableAttribute()]
    public partial class ProductsAndQty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderedQty {
            get {
                return this.orderedQtyField;
            }
            set {
                if ((this.orderedQtyField.Equals(value) != true)) {
                    this.orderedQtyField = value;
                    this.RaisePropertyChanged("orderedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsAndSchemes", Namespace="http://schemas.datacontract.org/2004/07/ServiceEndpoint")]
    [System.SerializableAttribute()]
    public partial class ProductsAndSchemes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsAndQty productqtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchemeObj[] schemesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductsAndQty productqty {
            get {
                return this.productqtyField;
            }
            set {
                if ((object.ReferenceEquals(this.productqtyField, value) != true)) {
                    this.productqtyField = value;
                    this.RaisePropertyChanged("productqty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchemeObj[] schemes {
            get {
                return this.schemesField;
            }
            set {
                if ((object.ReferenceEquals(this.schemesField, value) != true)) {
                    this.schemesField = value;
                    this.RaisePropertyChanged("schemes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Add", ReplyAction="http://tempuri.org/IService/AddResponse")]
        void Add(string name, string shortCode, string description, decimal price, string primaryCategoryShortCode, string secondaryShortCode, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Add", ReplyAction="http://tempuri.org/IService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(string name, string shortCode, string description, decimal price, string primaryCategoryShortCode, string secondaryShortCode, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Delete", ReplyAction="http://tempuri.org/IService/DeleteResponse")]
        void Delete(string shortCode, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Delete", ReplyAction="http://tempuri.org/IService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string shortCode, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Update", ReplyAction="http://tempuri.org/IService/UpdateResponse")]
        void Update(string name, string shortCode, string description, decimal price, int primaryCategoryId, int secondaryCategoryId, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Update", ReplyAction="http://tempuri.org/IService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string name, string shortCode, string description, decimal price, int primaryCategoryId, int secondaryCategoryId, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPrimaryCategories", ReplyAction="http://tempuri.org/IService/GetPrimaryCategoriesResponse")]
        void GetPrimaryCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPrimaryCategories", ReplyAction="http://tempuri.org/IService/GetPrimaryCategoriesResponse")]
        System.Threading.Tasks.Task GetPrimaryCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddScheme", ReplyAction="http://tempuri.org/IService/AddSchemeResponse")]
        void AddScheme(string name, string shortCode, string description, System.DateTime startdate, System.DateTime endDate, bool isExpired, decimal discountPercent, int unitsBooked, decimal revenueGenerated, string primaryCategoryShortCode, string secondaryCategoryCode, string productCode, string expiredBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddScheme", ReplyAction="http://tempuri.org/IService/AddSchemeResponse")]
        System.Threading.Tasks.Task AddSchemeAsync(string name, string shortCode, string description, System.DateTime startdate, System.DateTime endDate, bool isExpired, decimal discountPercent, int unitsBooked, decimal revenueGenerated, string primaryCategoryShortCode, string secondaryCategoryCode, string productCode, string expiredBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetScheme", ReplyAction="http://tempuri.org/IService/GetSchemeResponse")]
        SchemeObj[] GetScheme(string primaryCategoryCode, string secondaryCategoryCode, string productCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetScheme", ReplyAction="http://tempuri.org/IService/GetSchemeResponse")]
        System.Threading.Tasks.Task<SchemeObj[]> GetSchemeAsync(string primaryCategoryCode, string secondaryCategoryCode, string productCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSchemeForProducts", ReplyAction="http://tempuri.org/IService/GetSchemeForProductsResponse")]
        ProductsAndSchemes[] GetSchemeForProducts(ProductsAndQty[] products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSchemeForProducts", ReplyAction="http://tempuri.org/IService/GetSchemeForProductsResponse")]
        System.Threading.Tasks.Task<ProductsAndSchemes[]> GetSchemeForProductsAsync(ProductsAndQty[] products);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(string name, string shortCode, string description, decimal price, string primaryCategoryShortCode, string secondaryShortCode, string model) {
            base.Channel.Add(name, shortCode, description, price, primaryCategoryShortCode, secondaryShortCode, model);
        }
        
        public System.Threading.Tasks.Task AddAsync(string name, string shortCode, string description, decimal price, string primaryCategoryShortCode, string secondaryShortCode, string model) {
            return base.Channel.AddAsync(name, shortCode, description, price, primaryCategoryShortCode, secondaryShortCode, model);
        }
        
        public void Delete(string shortCode, string model) {
            base.Channel.Delete(shortCode, model);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string shortCode, string model) {
            return base.Channel.DeleteAsync(shortCode, model);
        }
        
        public void Update(string name, string shortCode, string description, decimal price, int primaryCategoryId, int secondaryCategoryId, string model) {
            base.Channel.Update(name, shortCode, description, price, primaryCategoryId, secondaryCategoryId, model);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string name, string shortCode, string description, decimal price, int primaryCategoryId, int secondaryCategoryId, string model) {
            return base.Channel.UpdateAsync(name, shortCode, description, price, primaryCategoryId, secondaryCategoryId, model);
        }
        
        public void GetPrimaryCategories() {
            base.Channel.GetPrimaryCategories();
        }
        
        public System.Threading.Tasks.Task GetPrimaryCategoriesAsync() {
            return base.Channel.GetPrimaryCategoriesAsync();
        }
        
        public void AddScheme(string name, string shortCode, string description, System.DateTime startdate, System.DateTime endDate, bool isExpired, decimal discountPercent, int unitsBooked, decimal revenueGenerated, string primaryCategoryShortCode, string secondaryCategoryCode, string productCode, string expiredBy) {
            base.Channel.AddScheme(name, shortCode, description, startdate, endDate, isExpired, discountPercent, unitsBooked, revenueGenerated, primaryCategoryShortCode, secondaryCategoryCode, productCode, expiredBy);
        }
        
        public System.Threading.Tasks.Task AddSchemeAsync(string name, string shortCode, string description, System.DateTime startdate, System.DateTime endDate, bool isExpired, decimal discountPercent, int unitsBooked, decimal revenueGenerated, string primaryCategoryShortCode, string secondaryCategoryCode, string productCode, string expiredBy) {
            return base.Channel.AddSchemeAsync(name, shortCode, description, startdate, endDate, isExpired, discountPercent, unitsBooked, revenueGenerated, primaryCategoryShortCode, secondaryCategoryCode, productCode, expiredBy);
        }
        
        public SchemeObj[] GetScheme(string primaryCategoryCode, string secondaryCategoryCode, string productCode) {
            return base.Channel.GetScheme(primaryCategoryCode, secondaryCategoryCode, productCode);
        }
        
        public System.Threading.Tasks.Task<SchemeObj[]> GetSchemeAsync(string primaryCategoryCode, string secondaryCategoryCode, string productCode) {
            return base.Channel.GetSchemeAsync(primaryCategoryCode, secondaryCategoryCode, productCode);
        }
        
        public ProductsAndSchemes[] GetSchemeForProducts(ProductsAndQty[] products) {
            return base.Channel.GetSchemeForProducts(products);
        }
        
        public System.Threading.Tasks.Task<ProductsAndSchemes[]> GetSchemeForProductsAsync(ProductsAndQty[] products) {
            return base.Channel.GetSchemeForProductsAsync(products);
        }
    }
}
